models/Noticias.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "noticias".
 *
 * @property int $id
 * @property string $titulo
 * @property string|null $fecha_publicacion
 * @property string|null $contenido
 * @property int|null $autor
 * @property int $publico
 *
 * @property Usuarios $autor
 */
class Noticias extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'noticias';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['titulo'], 'required'],
            [['fecha_publicacion'], 'safe'],
            [['autor', 'publico'], 'integer'],
            [['titulo'], 'string', 'max' => 255],
            [['contenido'], 'string', 'max' => 3000],
            [['autor'], 'exist', 'skipOnError' => true, 'targetClass' => Usuarios::class, 'targetAttribute' => ['autor' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'titulo' => 'Titulo',
            'fecha_publicacion' => 'Fecha Publicacion',
            'contenido' => 'Contenido',
            'autor' => 'Autor',
            'publico' => 'Público',
        ];
    }

    /**
    * Gets query for [[Autor]].
    *
    * @return \yii\db\ActiveQuery
    */
   public function getAutor()
   {
       return $this->hasOne(Usuarios::class, ['id' => 'autor']);
   }

    /**
     * Devuelve el nombre y apellidos del autor.
     * 
     * @return string
     */
    public function getAutorNombreApellidos()
    {
        // Usa la relación definida para obtener el autor
        return $this->getAutor()->one() ? $this->getAutor()->one()->nombre_apellidos : 'Desconocido';
    }
    
    public function getFechaFormateada() {
        if ($this->fecha_publicacion) {
            setlocale(LC_TIME, 'es_ES.UTF-8');
            $timestamp = strtotime($this->fecha_publicacion);
            return strftime('%d de %B de %Y', $timestamp);
            }
        return null;
    }
    
}         

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\data\ActiveDataProvider;
use app\models\Instrumentos;
use yii\helpers\FileHelper;
use yii\web\NotFoundHttpException;
use yii2mod\rbac\models\RouteModel;
use yii\rbac\Item;
use yii2mod\rbac\models\search\AuthItemSearch;
use app\models\Noticias;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $instrumentos= new ActiveDataProvider([
            'query' => Instrumentos::find()->select("*")
            
        ]);
        $noticias = new ActiveDataProvider([
        'query' => Noticias::find()
            ->where(['publico' => true])
            ->orderBy(['fecha_publicacion' => SORT_DESC]),
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');
            Yii::$app->mailer->compose()
                ->setFrom('pruebas@escuelacfc.com')
                ->setTo('saul.crespo.sc@gmail.com')
                ->setSubject('Test Email')
                ->setTextBody('This is a test email sent from Yii2.')
                ->send();
            return $this->refresh();
        }
        
        return $this->render('index',[
            'instrumentos' => $instrumentos->models,
            'noticias' => $noticias->getModels(),
            'model' => $model

        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('index#inicio');
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->actionLogin();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');
            Yii::$app->mailer->compose()
                ->setFrom('pruebas@escuelacfc.com')
                ->setTo('saul.crespo.sc@gmail.com')
                ->setSubject('Test Email')
                ->setTextBody('This is a test email sent from Yii2.')
                ->send();
            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionRbac()
    {
        $labels = [
        'Item' => 'Permission',
        'Items' => 'Permissions',
        ];
        // Initialize the RouteModel for managing routes
        $model = Yii::createObject(RouteModel::class);

        // Create the search model for managing items (roles/permissions)
        $searchModel = new AuthItemSearch();
        $searchModel->type = Item::TYPE_ROLE; // Assuming you're working with roles here

        // Get the data provider for displaying roles/permissions in GridView
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        // Render the 'rbac' view with the necessary data
        return $this->render('rbac', [
            'routes' => $model->getAvailableAndAssignedRoutes(),
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'labels' => $labels
        ]);
    }
    
    public function actionUpload()
    {
       
        
        $model = new UploadForm();

        if (Yii::$app->request->isPost) {
            $model->file = UploadedFile::getInstance($model, 'file');
            if ($model->validate()) {
                $filePath = ($model->file->extension==='mp4'?'videos/':'imagenes/') .
                                 $model->file->baseName . '.' . $model->file->extension; //);
                if ($model->file->saveAs($filePath)) {
                    Yii::$app->session->setFlash('success', 'El archivo ha sido subido exitosamente.');
                } else {
                    Yii::$app->session->setFlash('error', 'Hubo un error al subir el archivo.');
                }
                return $this->refresh();
            }
        }

        return $this->render('upload', ['model' => $model]);
    }

    public function actionFiles()
    {
       
        
        $files = array_merge(FileHelper::findFiles('imagenes'), FileHelper::findFiles('videos'));
        return $this->render('files', ['files' => $files]);
    }

    public function actionViewFile($filename)
    {
        $imagePath = 'imagenes/' . $filename;
        $videoPath = 'videos/' . $filename;

        // Check if file exists in either directory
        if (!file_exists(Yii::getAlias('@webroot/' . $imagePath)) && !file_exists(Yii::getAlias('@webroot/' . $videoPath))) {
            throw new NotFoundHttpException('The requested file does not exist.');
        }

        // Determine the correct file path to display
        $filePath = file_exists(Yii::getAlias('@webroot/' . $imagePath)) ? $imagePath : $videoPath;

        return $this->renderAjax('view-file', ['filePath' => $filePath, 'filename' => $filename]);

    }

    
    public function actionDownloadFile($filename)
    {
        
        
        $filePath = Yii::getAlias('@web/imagenes/' . $filename);
        if (!file_exists($filePath)) {
            $filePath = Yii::getAlias('@web/videos/' . $filename);
            if (!file_exists($filePath)) {
                throw new NotFoundHttpException('The requested file does not exist.');
            }
        }
        return Yii::$app->response->sendFile($filePath);
    }

    public function actionDeleteFile($filename)
    { 
        $filePath = Yii::getAlias('@webroot/imagenes/' . $filename);
        if (!file_exists($filePath)) {
            $filePath = Yii::getAlias('@webroot/videos/' . $filename);
        }

        if (file_exists($filePath)) {
            unlink($filePath);
            Yii::$app->session->setFlash('success', 'The file has been deleted successfully.');
        } else {
            Yii::$app->session->setFlash('error', 'There was an error deleting the file.');
        }
        return $this->redirect(['site/files']);
    }
    
    
}

views/site/about.php
<?php

use yii\widgets\ListView;
?>
<div class="container quienes-somos">
    <div class="title-somos d-flex justify-content-center flex-column align-items-center">
        <h2 class="mb-4 mt-5">¿Quiénes somos?</h2>
        <p>Somos Danza CFC , una escuela de danza cristiana dedicada a glorificar a Dios a través del arte del baile.
            Fundada con la pasión de integrar la fe y la expresión artística, nuestra institución se centra en proporcionar
            una formación de danza que no solo busca la excelencia técnica, sino que también fomenta el crecimiento espiritual
            y el desarrollo del carácter cristiano.<br>
            En Danza CFC, creemos que cada movimiento es una oportunidad para adorar y honrar a Dios. Nuestros programas están
            diseñados para todos los niveles y edades, desde principiantes hasta avanzados, ofreciendo una variedad de estilos
            de danza que incluyen danza con pandero, danza hebrea y profética, siempre con un enfoque en principios y valores cristianos.<br>
            Nuestro equipo está compuesto por instructores altamente calificados y apasionados, quienes no solo son expertos en su campo,
            sino también mentores comprometidos con el bienestar y crecimiento integral de nuestros estudiantes. Nos esforzamos por
            crear un ambiente de apoyo y amor, donde cada estudiante se sienta valorado y motivado a alcanzar su máximo potencial.<br>
            En Danza CFC, nuestra comunidad es una extensión de nuestra fe. Organizamos eventos, presentaciones y proyectos de servicio
            que permiten a nuestros estudiantes utilizar sus talentos para impactar positivamente a la comunidad y compartir el mensaje
            de esperanza y amor de Cristo.<br>
            Únete a nosotros en Danza CFC, donde la danza y la fe se unen para crear algo verdaderamente hermoso y
            significativo.
        </p>
    </div>

    <!-- VISIÓN Y MISIÓN POSIBLE -->
    <div class="row">
        <div class="col-6 d-flex align-items-center flex-column">
            <h3>Visión</h3>
            <p>"Ser una comunidad de fe donde la danza se convierte en una expresión viva de la adoración a Dios, inspirando y
                transformando vidas a través del arte y el compromiso cristiano. Aspiramos a ser un faro de luz y esperanza,
                promoviendo la excelencia en la danza mientras cultivamos valores de amor, fe y servicio en cada estudiante."
            </p>
        </div>
        <div class="col-6 d-flex align-items-center flex-column">
            <h3>Misión</h3>
            <p>"Nuestra misión es glorificar a Dios y edificar Su reino a través de la enseñanza de la danza. Nos dedicamos
                a proporcionar una formación integral que combina la excelencia técnica con el desarrollo espiritual.
                Fomentamos un ambiente donde los estudiantes pueden crecer en su fe, descubrir sus talentos dados por Dios
                y usar sus habilidades para impactar positivamente a la comunidad y el mundo. Nos comprometemos a inculcar
                valores cristianos, promoviendo el respeto, la humildad y el amor en todas nuestras actividades."
            </p>
        </div>
    </div>

    <div class="tarjetas-pasos d-flex justify-content-center mt-5">
        <div class="card card-tarjeta-pasos" style="width: 18rem;">
            <div class="contain-image">
                <img class="card-img-top" src="../../web/imagenes/Directora.jpg" alt="Card image cap">
            </div>
            <div class="card-body d-flex justify-content-center flex-column align-items-center">
                <h5 class="card-title text-center"> Directora <br>Fidelina Hamilton</h5>
                <p class="card-text text-center">
                     
                </p>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-6">
            <!-- TARJETA 1 -->
            <div class="tarjetas-pasos d-flex justify-content-center mt-5">
                <div class="card card-tarjeta-pasos" style="width: 18rem;">
                    <div class="contain-image">
                        <img class="card-img-top" src="../../web/imagenes/Lider.jpg" alt="Card image cap">
                    </div>
                    <div class="card-body d-flex justify-content-center flex-column align-items-center">
                        <h5 class="card-title text-center">Líder <br>Helena Canty</h5>
                        <p class="card-text text-center">

                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <!-- TARJETA 2 -->
            <div class="tarjetas-pasos d-flex justify-content-center mt-5">
                <div class="card card-tarjeta-pasos" style="width: 18rem;">
                    <div class="contain-image">
                        <img class="card-img-top" src="../../web/imagenes/Secretaria.jpg" alt="Card image cap">
                    </div>
                    <div class="card-body d-flex justify-content-center flex-column align-items-center">
                        <h5 class="card-title text-center">Secretaria<br> Keyla Mccue</h5>
                        <p class="card-text text-center">
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contacto';
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Gracias por contactar con nosotros. Responderemos a la mayor brevedad posible.
        </div>

        <p>
            
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Puedes ver el email resultante en:  <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            Si tienes preguntas acerca de la inscripción, contacta con nosotros por medio de este formulario, o bien escríbenos un whatsapp.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
    <div class="col-md-5">
        <!-- Incluir la vista parcial del mapa -->
        <?= $this->render('map') ?>
    </div>
    <div class="Whatsapp row">
        <h1 class="center">Contacta con nosotros</h1>
        <p>
            Puedes contactarnos directamente a través de WhatsApp haciendo clic en el siguiente enlace:
        </p>

        <p>
            <?= Html::a('Contáctanos por WhatsApp', 'https://api.whatsapp.com/send?phone=+34605594430&text=Hola%20me%20gustaria%20obtener%20informacion', ['class' => 'btn btn-success']) ?>
        </p>

    </div>
</div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap4\ActiveForm;
use yii\captcha\Captcha;

/** @var yii\web\View $this */

$this->title = 'My Yii Application';
?>
<div id="inicio" class="site-index">

    <div class="jumbotron text-center bg-transparent" style="height: 100vh; background-image: url('<?= Yii::getAlias('@web/imagenes/banner.png') ?>'); background-size: cover; background-position: center; display: flex; justify-content: center; align-items: center;">
        <div style="background-color: rgba(0, 0, 0, 0.5); padding: 20px; border-radius: 10px;">
            <h1 class="display-4 text-white">Escuela de Danza</h1>
            <p class="lead text-white">Centro Familiar Cristiano Santander</p>
        </div>
    </div>

    
    <div class="body-content">
        <div class="jumbotron d-flex justify-content-center bg-transparent pb-2">
            <h2 id="instrumentos"> Instrumentos</h2>
        </div>

        <div class="row">
            <?php foreach ($instrumentos as $instrumento): ?>
                <div class="col-lg-3">
                    <div class="card" style="height:400px; background-image: url('<?= Yii::getAlias('@web/imagenes/instrumentos/' . $instrumento->nombre . ".jpg") ?>'); background-size: cover; background-position: center; transition: transform 0.3s;">
                        <div class="card-body d-flex flex-column justify-content-end" style="background-color: rgba(255, 255, 255, 0.65);">
                            <h2 class="card-title"><?= Html::encode($instrumento->nombre) ?></h2>
                            <p><a class="btn btn-outline-secondary" href="<?= Url::to(['instrumentos/view', 'id' => $instrumento->id]) ?>">Ver detalles &raquo;</a></p>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

    </div>
    
    <div class="noticias-read container mt-4">

    <h2 id="noticias" class="mb-4 text-center">Noticias</h2>

    <?php foreach ($noticias as $noticia): ?>
    <div class="row mb-3 news-item">
        <div class="col-md-8">
            <h3><?= Html::encode($noticia->titulo) ?></h3>
            <p class="text-muted">
                Autor: <?= Html::encode($noticia->autorNombreApellidos) ?>
            </p>
            <p style="text-align: justify;">
                <?= nl2br(Html::encode($noticia->contenido)) ?>
            </p>
        </div>
        <div class="col-md-4 text-right">
            <p class="text-muted">
                Fecha de publicación: <?= $noticia->getFechaFormateada() ?>
            </p>
        </div>
    </div>
<?php endforeach; ?>
</div>
    
<div class="container quienes-somos">
    <div class="title-somos d-flex justify-content-center flex-column align-items-center">
        <h2 id="about" class="mb-4 mt-5">¿Quiénes somos?</h2>
        <p>Somos Danza CFC , una escuela de danza cristiana dedicada a glorificar a Dios a través del arte del baile.
            Fundada con la pasión de integrar la fe y la expresión artística, nuestra institución se centra en proporcionar
            una formación de danza que no solo busca la excelencia técnica, sino que también fomenta el crecimiento espiritual
            y el desarrollo del carácter cristiano.<br>
            En Danza CFC, creemos que cada movimiento es una oportunidad para adorar y honrar a Dios. Nuestros programas están
            diseñados para todos los niveles y edades, desde principiantes hasta avanzados, ofreciendo una variedad de estilos
            de danza que incluyen danza con pandero, danza hebrea y profética, siempre con un enfoque en principios y valores cristianos.<br>
            Nuestro equipo está compuesto por instructores altamente calificados y apasionados, quienes no solo son expertos en su campo,
            sino también mentores comprometidos con el bienestar y crecimiento integral de nuestros estudiantes. Nos esforzamos por
            crear un ambiente de apoyo y amor, donde cada estudiante se sienta valorado y motivado a alcanzar su máximo potencial.<br>
            En Danza CFC, nuestra comunidad es una extensión de nuestra fe. Organizamos eventos, presentaciones y proyectos de servicio
            que permiten a nuestros estudiantes utilizar sus talentos para impactar positivamente a la comunidad y compartir el mensaje
            de esperanza y amor de Cristo.<br>
            Únete a nosotros en Danza CFC, donde la danza y la fe se unen para crear algo verdaderamente hermoso y
            significativo.
        </p>
    </div>

    <!-- VISIÓN Y MISIÓN POSIBLE -->
    <div class="row">
        <div class="col-6 d-flex align-items-center flex-column">
            <h3>Visión</h3>
            <p>"Ser una comunidad de fe donde la danza se convierte en una expresión viva de la adoración a Dios, inspirando y
                transformando vidas a través del arte y el compromiso cristiano. Aspiramos a ser un faro de luz y esperanza,
                promoviendo la excelencia en la danza mientras cultivamos valores de amor, fe y servicio en cada estudiante."
            </p>
        </div>
        <div class="col-6 d-flex align-items-center flex-column">
            <h3>Misión</h3>
            <p>"Nuestra misión es glorificar a Dios y edificar Su reino a través de la enseñanza de la danza. Nos dedicamos
                a proporcionar una formación integral que combina la excelencia técnica con el desarrollo espiritual.
                Fomentamos un ambiente donde los estudiantes pueden crecer en su fe, descubrir sus talentos dados por Dios
                y usar sus habilidades para impactar positivamente a la comunidad y el mundo. Nos comprometemos a inculcar
                valores cristianos, promoviendo el respeto, la humildad y el amor en todas nuestras actividades."
            </p>
        </div>
    </div>

    <div class="row">
    <!-- Tarjeta Directora -->
    <div class="col-lg-4">
        <div class="card" style="height:400px; background-image: url('<?= Yii::getAlias('@web/imagenes/Directora.jpg') ?>'); background-size: cover; background-position: center; transition: transform 0.3s;">
            <div class="card-body d-flex flex-column justify-content-end" style="background-color: rgba(255, 255, 255, 0.65);">
                <h5 class="card-title text-center">Directora</h5>
                <p class="card-text text-center">Fidelina Hamilton</p>
            </div>
        </div>
    </div>

    <!-- Tarjeta Líder -->
    <div class="col-lg-4">
        <div class="card" style="height:400px; background-image: url('<?= Yii::getAlias('@web/imagenes/Lider.jpg') ?>'); background-size: cover; background-position: center; transition: transform 0.3s;">
            <div class="card-body d-flex flex-column justify-content-end" style="background-color: rgba(255, 255, 255, 0.65);">
                <h5 class="card-title text-center">Líder</h5>
                <p class="card-text text-center">Helena Canty</p>
            </div>
        </div>
    </div>

    <!-- Tarjeta Secretaria -->
    <div class="col-lg-4">
        <div class="card" style="height:400px; background-image: url('<?= Yii::getAlias('@web/imagenes/Secretaria.jpg') ?>'); background-size: cover; background-position: center; transition: transform 0.3s;">
            <div class="card-body d-flex flex-column justify-content-end" style="background-color: rgba(255, 255, 255, 0.65);">
                <h5 class="card-title text-center">Secretaria</h5>
                <p class="card-text text-center">Keyla Mccue</p>
            </div>
        </div>
    </div>
</div>

</div> 
<div class="site-contact">
    <h1 id="contact">Contacto</h1>
    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Gracias por contactar con nosotros. Responderemos a la mayor brevedad posible.
        </div>

        <p>
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Puedes ver el email resultante en: <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            Si tienes preguntas acerca de la inscripción, contacta con nosotros por medio de este formulario, o bien escríbenos un whatsapp.
        </p>

        <div class="row">
            <!-- Columna izquierda para el formulario -->
            <div class="col-lg-6 col-md-6">
                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput() ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>
            </div>

            <!-- Columna derecha para el mapa y el botón de WhatsApp -->
            <div class="col-lg-6 col-md-6">
                <!-- Mapa -->
                <?= $this->render('map') ?>

                <!-- Botón de WhatsApp -->
                <div class="Whatsapp">
                    <p>Puedes contactarnos directamente a través de WhatsApp haciendo clic en el siguiente enlace:</p>
                    <p>
                        <?= Html::a('Contáctanos por WhatsApp', 'https://api.whatsapp.com/send?phone=+34605594430&text=Hola%20me%20gustaria%20obtener%20informacion', ['class' => 'btn btn-success']) ?>
                    </p>
                </div>
            </div>
        </div>

    <?php endif; ?>
</div>

<?php
// Añadimos los estilos de hover al final del archivo para hacer que las tarjetas se agranden al pasar el ratón
$this->registerCss("
    .card:hover {
        transform: scale(1.05);
    }
");
?>

views/site/login.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap4\ActiveForm $form */
/** @var app\models\LoginForm $model */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Entrar';
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Introduzca usuario o correo electrónico y contraseña para entrar:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{input}\n{error}",
            'labelOptions' => ['class' => 'col-lg-2 col-form-label mr-lg-3'],
            'inputOptions' => ['class' => 'col-lg-4 form-control'],
            'errorOptions' => ['class' => 'col-lg-6 invalid-feedback'],
        ],
    ]); ?>

        <?= $form->field($model, 'usernameOrEmail')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
           'class' => 'custom-control-input',
            'labelOptions' => ['class' => 'custom-control-label'],
            'template' => "<div class=\"offset-lg-2 col-lg-4 custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-6\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="offset-lg-2 col-lg-10">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

</div>